version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      # MYSQL_DATABASE: 'project'
      # MYSQL_USER: 'app'
      # MYSQL_PASSWORD: 'group10'
      MYSQL_ROOT_PASSWORD: 'group10'
    ports:
      - "33061:3306"
    command: --init-file /data/application/mysql_init.sql
    volumes:
      - prj-mysql-data:/var/lib/mysql
      - ./mysql_init.sql:/data/application/mysql_init.sql
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: group10
      MONGO_INITDB_DATABASE: project
    ports:
      - 27017:27017
    volumes:
      - prj-mongodb-data:/data/db
  
  analytics-app:
    image: akinofu/analytics-app:latest
    restart: always
    command: python3 /analytics-app/app.py
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - mongodb
  
  front:
    image: cherylk19/front:latest
    restart: always
    build: .
    # command: node server.js
    ports:
      - 3001:3001
    depends_on:
      - mysql
      - mongodb
  
  auth:
    image: cherylk19/auth:latest
    restart: always
    build: .
    # command: node server.js
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - mongodb

  data:
    image: cherylk19/data:latest
    restart: always
    build: .
    # command: node server.js
    ports:
      - 3002:3002
    depends_on:
      - mysql
      - mongodb

  # web-app:
  #   image: cherylk19/webapp:v1
  #   restart: always
  #   build: .
  #   # command: node server.js
  #   ports:
  #     - 8001:8001
  #   depends_on:
  #     - mysql
  #     - mongodb

volumes:
  prj-mysql-data:
  prj-mongodb-data:
