apiVersion: v1
kind: Pod
metadata:
  name: authentication
  labels:
    name: auth
spec:
  containers:
  - name: auth
    image: cherylk19/auth:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000