apiVersion: v1
kind: Pod
metadata:
  name: data
  labels:
    name: data
spec:
  containers:
  - name: data
    image: cherylk19/data:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3002
