apiVersion: v1
kind: Pod
metadata:
  name: analytics
  labels:
    name: analytics
spec:
  containers:
  - name: myapp
    image: akinofu/analytics-app:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080