apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradeapp-auth
  labels:
    app: gradeapp-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradeapp-auth
  template:
    metadata:
      labels:
        app: gradeapp-auth
    spec: 
      terminationGracePeriodSeconds: 60
      containers:
      - name: gradeapp-auth
        image: cherylk19/auth
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: gradeapp-auth

