# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-secret
# data:
#   MONGO_INITDB_ROOT_USERNAME: cm9vdAo=
#   MONGO_INITDB_ROOT_PASSWORD: Z3JvdXAxMAo=
#   MONGO_INITDB_DATABASE: cHJvamVjdAo=
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: prj-mongodb-data
# spec:
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /data/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  labels:
    app: gradeapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradeapp-mongodb
  labels:
    app: gradeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gradeapp
      tier: mongodb
  strategy: {}
  template:
    metadata:
      labels:
        app: gradeapp
        tier: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          args: ["--dbpath","/data/db"]
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
            # valueFrom: 
            #   secretKeyRef:
            #     name: mongo-creds
            #     key: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: group10
            # valueFrom:
            #   secretKeyRef:
            #     name: mongo-creds
            #     key: group10
          - name: MONGO_INITDB_DATABASE
            value: project
          volumeMounts:
          - name: mongo-persistent-storage
            mountPath: "/data/db"
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim

