apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    create database if not exists project;
    use project;
    create table if not exists grades (
      name varchar(250) not null,
      subject varchar(250) not null,
      grade int not null);