apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: analytics-app
  name: analytics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analytics-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: analytics-app
    spec:
      containers:
        - args:
            - python3
            - /analytics-app/app.py
          image: akinofu/analytics-app:latest
          name: analytics-app
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
