apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ..\docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: group10
            - name: MYSQL_DATABASE
              value: project
            - name: MYSQL_PASSWORD
              value: group10
            - name: MYSQL_USER
              value: backend
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: prj-mysql-data
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: prj-mysql-data
          persistentVolumeClaim:
            claimName: prj-mysql-data
        # - name: mysql-claim1
        #   persistentVolumeClaim:
        #     claimName: mysql-claim1
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
status: {}
